### PR TITLE
Update characteristics.md

### PR DESCRIPTION
**Pull request by NorthernMan54**
Fix for https://github.com/homebridge/homebridge/issues/3698

### CODE REVIEW

**Comment by bwp91** [comment]
are these docs auto generated from any code? i don’t know much about this repo @NorthernMan54

**Comment by NorthernMan54** [comment]
No, this section is all hand written

**Review by Supereg — APPROVED** [review]
Looks good 👍

**Comment by hjdhjd** [comment]
We might want to further revise this first…there are good reasons to implement an `onGet` even when you use `updateValue`. For example - you want to execute a realtime refresh of the value in question.

**Pull request merged**
